language: SourcePAWN
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

#Set the build environment
env:
  matrix:
  - SMVERSION=1.9

#And compile!
install:
    - cd $HOME/build/kossolax/rebels-corp/
    - wget http://sourcemod.net/smdrop/$SMVERSION/ -O - | grep "\.tar\.gz" | sed 's/^.*"sourcemod/sourcemod/;s/\.tar\.gz".*$/.tar.gz/' | tail --lines=1 > sourcemod
    - wget --input-file=sourcemod --base=http://sourcemod.net/smdrop/$SMVERSION/
    - tar -xzf $(cat sourcemod) --exclude='addons/sourcemod/scripting/*.sp'

before_script:
    - git pull origin $TRAVIS_BRANCH
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - mkdir $HOME/compiled/
    - chmod 777 $HOME/compiled/

script:
    - cd $HOME/build/kossolax/rebels-corp/addons/sourcemod/scripting/
    - for i in ./*.sp; do echo -e "\n\n----------------------------------------------------------------------------\nCompiling... $i"; ./spcomp -i include/ -i custom_include/ $i -o=$HOME/compiled/`basename $i | cut -d. -f1` -O2; RETVAL=$?; if [ $RETVAL -ne 0 ]; then exit 1; fi; done;
    - for i in ./*/*.sp; do echo -e "\n\n----------------------------------------------------------------------------\nCompiling... $i"; ./spcomp -i include/ -i custom_include/ $i -o=$HOME/compiled/`basename $i | cut -d. -f1` -O2; RETVAL=$?; if [ $RETVAL -ne 0 ]; then exit 1; fi; done;

before_deploy:
    - git tag $TRAVIS_BUILD_NUMBER

deploy:
  provider: releases
  api_key:
    secure: mEjv47KPCcKtSy+4B43N0sNZcOwfpY2sasuzDbTBC02dOki0CzSCok3wF2Zxb6PiZMNWeX22FGIakL2TkKI6TwqdcdM7TJOuUJ2XeGigxaZTcfoyczbuk7aX7yu59Moy736aufqkoN7qHLVgqA9MmTrAwl1Ew2OKnwkJacUUfzz7X/ILFQ6YFz3TDnym5VZG+36HTx6lDXUrjnczBKb2eYRbgduXFzCI8MZ4Inbqb6m/SRKlFBvpFWNbIqiJif37qGz46VdMPx38BMEkl0i/OUYQc3hpQ02ZFKpLWzvdYHr5bIETNAXYewkNOt5PPFi1d0nDhO1Ac/nTtp8yczqto7t5LyMu9NUUr+u2SUgWgXcyM15Hm8oboGgzJImPRFsYv3TTFgmibu3wg4nmIwUccfPGHEWPw2zuC/GIz6ymgRwxegJW7jTNUJcEvnr6BUj5Nz3ff4Wz+L3V+JUdkhxaM0K3htFYOn+TNhF/p0o1F9fl6zz0OKB6T6XFQ5115yApkshHhkxNXNSbdpfDRxioTXze5nU/BnQT5v/esA/BAczV4BnCOgB+bn+wr/M5r3Bhf3dcYoUkA6ruT8CZmDSfrRqp5+csZbxvuhVjDCkHu+fPeAfSma0qhrByxzUu/Dp7Ef0J/JAcPcAEasXRWxuqHNMXykQEcSk+WdXfTv07DUg=
  file_glob: true
  file: $HOME/compiled/*.smx
  skip_cleanup: true
  on:
    repo: kossolax/rebels-corp
